### PR TITLE
Add gnome-shell 43.x compatibility

### PR DESCRIPTION
**Pull request by halfa**
Tested under Fedora 37 workstation beta with gnome-shell 43.0.
Work fine, just the usual warnings for `meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed`.

### CODE REVIEW

**Comment by halfa** [comment]
The Fedora 37 vagrant image (`fedora/37-cloud-base`) is not available yet

**Comment by psydvl** [comment]
Works fine under latest openSUSE Tumbleweed

**Comment by psydvl** [comment]
Works fine under latest openSUSE Tumbleweed

**Comment by amezin** [comment]
> The Fedora 37 vagrant image (fedora/37-cloud-base) is not available yet

https://app.vagrantup.com/fedora/boxes/37-beta-cloud-base
Ubuntu 22.10 would be nice too: https://app.vagrantup.com/ubuntu/boxes/kinetic64

Also, test containers are necessary for at least one (or, ideally, both) of these distros: https://github.com/ddterm/gnome-shell-pod
Actually, test containers are more important than Vagrant VMs.

**Comment by amezin** [comment]
https://github.com/ddterm/gnome-shell-pod/pkgs/container/gnome-shell-pod%2Ffedora-37
https://github.com/ddterm/gnome-shell-pod/pkgs/container/gnome-shell-pod%2Fubuntu-22.10

**Pull request merged**
