### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by daPhipz**
I am a member of the German translation team over at [Damned Lies](https://l10n.gnome.org/users/daPhipz/), the official translation platform for GNOME.

I had a look at the translations and adjusted the German translation to better adhere with our standards, so that the extension feels more "one" with the whole desktop.

Feel free to have it proofread by another German contributor and ping me if another release is approaching with new strings to translate ;)

### CODE REVIEW

**Comment by amezin** [comment]
> ping me if another release is approaching with new strings to translate

inviting you to the org

**Comment by DasJott** [comment]
Thank you.
Yes I will have a look at the changes.

**Comment by amezin** [comment]
@DasJott So, do you have any objections to these changes?

**Comment by DasJott** [comment]
Okay, I checked and finished all new strings.
Even found some minor typos in the existing ones, as I went through all strings again.

**Comment by daPhipz** [comment]
I rebased this branch on `master` and translated some more new strings.
@DasJott Where did you correct the typos? I could not find any PRs or commits... :see_no_evil:

**Comment by amezin** [comment]
> Where did you correct the typos? I could not find any PRs or commits... 🙈

On Weblate apparently

https://github.com/ddterm/gnome-shell-extension-ddterm/pull/584/commits/13639b6ad87d1b2acf4998e4edb16413e5eb3fb5

**Comment by amezin** [comment]
So I tried to merge changes from Weblate, and there were following conflicts:

```diff
@@@ -109,7 -106,7 +109,11 @@@ msgstr "Schließen
  
  #: ddterm/app/menus.ui:97 ddterm/app/menus.ui:228
  msgid "Keep Open After Exit"
++<<<<<<< HEAD
 +msgstr "Nach dem Verlassen offen halten"
++=======
+ msgstr "Nach dem Beenden geöffnet lassen"
++>>>>>>> origin/weblate
  
  #: ddterm/app/menus.ui:103
  msgid "New Tab"
@@@ -135,7 -132,7 +139,11 @@@ msgstr "Neuer Reiter nach dem letzten R
  
  #: ddterm/app/menus.ui:124 ddterm/app/menus.ui:261
  msgid "Layout"
++<<<<<<< HEAD
 +msgstr "Anordnung"
++=======
+ msgstr "Darstellung"
++>>>>>>> origin/weblate
  
  #: ddterm/app/menus.ui:127 ddterm/app/menus.ui:264 ddterm/app/menus.ui:294
  msgid "No Split"
@@@ -266,7 -262,7 +273,11 @@@ msgstr "Finde vorheriges
  
  #: ddterm/app/terminalpage.js:440
  msgid "Restart"
++<<<<<<< HEAD
 +msgstr "Neu starten"
++=======
+ msgstr "Neustart"
++>>>>>>> origin/weblate
  
  #: ddterm/app/terminalpage.js:441 ddterm/app/terminalpage.js:616
  msgid "Close Terminal"
@@@ -274,11 -270,11 +285,19 @@@ msgstr "Terminal schließen
  
  #: ddterm/app/terminalpage.js:464
  msgid "The child process exited with status:"
++<<<<<<< HEAD
 +msgstr "Der Unterprozess wurde mit folgendem Status beendet:"
 +
 +#: ddterm/app/terminalpage.js:474
 +msgid "The child process was aborted by signal:"
 +msgstr "Der Unterprozess wurde durch folgendes Signal abgebrochen:"
++=======
+ msgstr "Der Unterprozess endete mit Status:"
+ 
+ #: ddterm/app/terminalpage.js:474
+ msgid "The child process was aborted by signal:"
+ msgstr "Der Unterprozess wurde abgebrochen durch Signal:"
++>>>>>>> origin/weblate
  
  #: ddterm/app/terminalpage.js:608
  msgid "Close this terminal?"
@@@ -476,11 -472,11 +495,19 @@@ msgstr "Dauer der Animation beim _Verbe
  
  #: ddterm/pref/glade/prefs-animation.ui:297
  msgid "_Show animation duration:"
++<<<<<<< HEAD
 +msgstr "_Dauer der Animation beim _Anzeigen:"
 +
 +#: ddterm/pref/glade/prefs-behavior.ui:39
 +msgid "_Resizable"
 +msgstr "g_rößenveränderbar"
++=======
+ msgstr "_Dauer der Animation beim Anzeigen:"
+ 
+ #: ddterm/pref/glade/prefs-behavior.ui:39
+ msgid "_Resizable"
+ msgstr "In der Größe veränderbar"
++>>>>>>> origin/weblate
  
  #: ddterm/pref/glade/prefs-behavior.ui:55
  msgid "_Above all windows"
@@@ -732,7 -728,7 +759,11 @@@ msgstr "Palette Farbe 15
  
  #: ddterm/pref/glade/prefs-colors.ui:634
  msgid "Show bold text in _bright colors"
++<<<<<<< HEAD
 +msgstr "Fetten Text in _hellen Farben anzeigen"
++=======
+ msgstr "Zeige fetten Text in hellen Farben"
++>>>>>>> origin/weblate
  
  #: ddterm/pref/glade/prefs-colors.ui:650
  msgid "Copy profile from GNOME Terminal"
@@@ -921,7 -917,7 +952,11 @@@ msgstr "_Bildlaufleiste anzeigen
  
  #: ddterm/pref/glade/prefs-scrolling.ui:60
  msgid "Scroll on _output"
++<<<<<<< HEAD
 +msgstr "Scrollen durch _Ausgabe"
++=======
+ msgstr "Scrollen bei Ausgabe"
++>>>>>>> origin/weblate
  
  #: ddterm/pref/glade/prefs-scrolling.ui:76
  msgid "Scroll on _keystroke"
@@@ -1078,7 -1073,7 +1112,11 @@@ msgstr "Tastenkürzel
  
  #: ddterm/pref/glade/prefs-shortcuts.ui:528
  msgid "Reset All Shortcuts to Defaults"
++<<<<<<< HEAD
 +msgstr "Alle Tastenkürzel auf Standardwerte zurücksetzen"
++=======
+ msgstr "Tastenkombinationen auf Standard zurücksetzen"
++>>>>>>> origin/weblate
  
  #: ddterm/pref/glade/prefs-tabs.ui:44
  msgid "Expand tabs"
```

I took @DasJott changes (`origin/weblate`) assuming they're newer. But please double-check.

Using two different tools for the same translation (GitHub PRs and Weblate) creates chaos. @daPhipz Could you please try using Weblate?

**Comment by DasJott** [comment]
I am sorry. I only knew about Weblate and so I made all changes there.

**Pull request merged**
